FROM node:8

WORKDIR /app 

COPY . /app 
ENV BASE_URL="https://hazy-api-nainemom.fandogh.cloud" 
ENV DIRECTION="ltr" 
ENV HOST="0.0.0.0" 
ENV PORT="3003" 
ENV NODE_ENV="production" 
ENV NPM_CONFIG_PRODUCTION="false" 
ENV RECAPTCHA_SITE_KEY="6Lfj3HwUAAAAAGKohyJRasw6EsMoQGu2i0dOw1Ti" 
ENV FIREBASE_API_KEY="AIzaSyCpRi2Rbkb-JNyXjaQTT_3YoN-1FdzkmwA"
ENV FIREBASE_PROJECT_ID="hazy-223207"
ENV FIREBASE_MESSAGING_SENDER_ID="432488206155"
EXPOSE 3003
RUN npm install 
RUN npm run build 
CMD ["npm","start"]

